# -*- coding: utf-8 -*-
"""id3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zehkGFU0iPfZ8AiZqq4vXvz_ej7K0yBe
"""

#id3
import pandas as pd
import numpy as np
data=pd.read_csv('/content/PlayTennis.csv')
data
from sklearn.preprocessing import LabelEncoder
edc=LabelEncoder()
data=data.apply(LabelEncoder().fit_transform)
data
x=data.iloc[:,:-1]
x
y=data.iloc[:,4]
y
from sklearn.tree import DecisionTreeClassifier
regressor=DecisionTreeClassifier()
dt_clf=DecisionTreeClassifier(criterion="entropy")
dt_clf.fit(x,y)
dt_clf.score(x,y)
y_pred=dt_clf.predict(x)
print(y)
print(y_pred)
from sklearn import tree
tree.plot_tree(dt_clf)