# -*- coding: utf-8 -*-
"""K means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPOOKiBYzDJNv5zAi2KvzmykV9AXmT7p
"""

#k mean em alg
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
import sklearn.metrics as metrics
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
df=pd.read_csv('/content/heart.csv')
x=df[['trestbps','chol','thalach']]
y=df['target']
# K-PLOT
model=KMeans(n_clusters=3, random_state=0).fit(x)
print('The accuracy score of K-Mean: ',metrics.accuracy_score(y, model.labels_))
print('The Confusion matrixof K-Mean:\n',metrics.confusion_matrix(y, model.labels_))
# GMM PLOT
gmm=GaussianMixture(n_components=3, random_state=0).fit(x)
y_cluster_gmm=gmm.predict(x)
print('The accuracy score of EM: ',metrics.accuracy_score(y, y_cluster_gmm))
print('The Confusion matrix of EM:\n ',metrics.confusion_matrix(y, y_cluster_gmm))